---
- hosts:        hosts_dotfiles
  gather_facts: false
  tasks:
    - include: tasks/101.shared.yml
      name: "\x1b[35;4m--- SHARED DOTFILES              ---\x1b[0m"
      tags: shared
    - include: tasks/102.shared_skel.yml
      name: "\x1b[35;4m--- SHARED DOTFILES (/etc/skel/) ---\x1b[0m"
      tags: shared_skel
    - include: tasks/103.local.yml
      name: "\x1b[35;4m--- LOCAL DOTFILES               ---\x1b[0m"
      tags: local
    - include: tasks/104.irssi.yml
      name: "\x1b[35;4m--- IRSSI                        ---\x1b[0m"
      tags: irssi
  vars:         ['ansible_ssh_pipelining': yes]
