---
- name: Transfer shared dotfiles
  synchronize:
    dest: .
    group: no
    owner: no
    rsync_opts:
      - "--exclude=_obsolete_"
      - "--exclude=.git"
      - "--exclude=.gitignore"
      - "--exclude=.gitmodules"
      - "--exclude=.irssi"
      - "--include=.**"
      - "--exclude=*"
    src: "."
    use_ssh_args: yes
