---
- local_action: stat path="{{ansible_ssh_user}}@{{ansible_host}}"
  name: Get file stat(2)us of user- and host-local dotfiles
  register: stat_result
- name: Transfer user- and host-local dotfiles
  synchronize:
    dest: .
    group: no
    owner: no
    rsync_opts:
      - "--exclude=_obsolete_"
      - "--exclude=.git"
      - "--exclude=.gitignore"
      - "--exclude=.irssi"
      - "--include=.**"
      - "--exclude=*"
    src: "../dotfiles_private/{{ansible_ssh_user}}@{{ansible_host}}/"
    use_ssh_args: yes
  when: stat_result.stat.exists
